name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'prompt_decorators/**'
      - 'registry/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is required for gh-deploy to work
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for git-revision-date-localized-plugin

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install all requirements explicitly to ensure they're properly installed
          pip install mkdocs>=1.5.0
          pip install mkdocs-material>=9.0.0
          pip install mkdocs-awesome-pages-plugin>=2.9.0
          pip install mkdocs-autolinks-plugin>=0.7.0
          pip install mkdocs-git-revision-date-localized-plugin>=1.2.0
          pip install mkdocs-minify-plugin>=0.7.0
          pip install mkdocstrings>=0.24.0
          pip install mkdocstrings-python>=1.7.0
          # Install the rest of the requirements
          pip install -r docs/requirements.txt

          # Verify plugins are installed
          pip list | grep mkdocs

      - name: Debug installed plugins
        run: |
          echo "Checking if awesome-pages plugin is installed:"
          pip show mkdocs-awesome-pages-plugin
          echo "Checking all installed mkdocs plugins:"
          pip list | grep mkdocs
          echo "Running plugin check script:"
          python scripts/check_mkdocs_plugins.py

      - name: Build documentation
        run: |
          mkdocs build

      - name: Deploy documentation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
